import type {
  Product, Seller, Category, FlashSale, Review, Notification,
  Testimonial, Stat, Banner, AISuggestion
} from "@/types";

// ===== Complete Categories =====
export const categories: Category[] = [
  { id: "c1", name: "Phones & Tablets", slug: "phones-tablets", icon: "smartphone", image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&q=80", productCount: 12450, subcategories: [{ id: "sc1a", name: "Smartphones", slug: "smartphones", productCount: 8900 }, { id: "sc1b", name: "Tablets", slug: "tablets", productCount: 2100 }, { id: "sc1c", name: "Accessories", slug: "phone-accessories", productCount: 1450 }] },
  { id: "c2", name: "Computers", slug: "computers", icon: "laptop", image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80", productCount: 8700, subcategories: [{ id: "sc2a", name: "Laptops", slug: "laptops", productCount: 3400 }, { id: "sc2b", name: "Desktops", slug: "desktops", productCount: 1800 }, { id: "sc2c", name: "Components", slug: "components", productCount: 3500 }] },
  { id: "c3", name: "Electronics", slug: "electronics", icon: "headphones", image: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=400&q=80", productCount: 15600, subcategories: [{ id: "sc3a", name: "Audio", slug: "audio", productCount: 4200 }, { id: "sc3b", name: "Cameras", slug: "cameras", productCount: 2300 }, { id: "sc3c", name: "Wearables", slug: "wearables", productCount: 5100 }, { id: "sc3d", name: "Smart Home", slug: "smart-home", productCount: 4000 }] },
  { id: "c4", name: "Fashion", slug: "fashion", icon: "shirt", image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&q=80", productCount: 32100, subcategories: [{ id: "sc4a", name: "Men", slug: "men-fashion", productCount: 12000 }, { id: "sc4b", name: "Women", slug: "women-fashion", productCount: 15000 }, { id: "sc4c", name: "Kids", slug: "kids-fashion", productCount: 5100 }] },
  { id: "c5", name: "Shoes", slug: "shoes", icon: "footprints", image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&q=80", productCount: 12400, subcategories: [{ id: "sc5a", name: "Sneakers", slug: "sneakers", productCount: 5600 }, { id: "sc5b", name: "Formal", slug: "formal-shoes", productCount: 2800 }, { id: "sc5c", name: "Sandals", slug: "sandals", productCount: 4000 }] },
  { id: "c6", name: "Beauty", slug: "beauty", icon: "sparkles", image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&q=80", productCount: 18900, subcategories: [{ id: "sc6a", name: "Skincare", slug: "skincare", productCount: 6700 }, { id: "sc6b", name: "Makeup", slug: "makeup", productCount: 5400 }, { id: "sc6c", name: "Hair Care", slug: "hair-care", productCount: 4800 }, { id: "sc6d", name: "Fragrance", slug: "fragrance", productCount: 2000 }] },
  { id: "c7", name: "Groceries", slug: "groceries", icon: "shopping-bag", image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&q=80", productCount: 23400, subcategories: [{ id: "sc7a", name: "Fresh Food", slug: "fresh-food", productCount: 8900 }, { id: "sc7b", name: "Beverages", slug: "beverages", productCount: 6700 }, { id: "sc7c", name: "Snacks", slug: "snacks", productCount: 7800 }] },
  { id: "c8", name: "Furniture", slug: "furniture", icon: "armchair", image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80", productCount: 8700, subcategories: [{ id: "sc8a", name: "Living Room", slug: "living-room", productCount: 3400 }, { id: "sc8b", name: "Bedroom", slug: "bedroom", productCount: 2800 }, { id: "sc8c", name: "Office", slug: "office-furniture", productCount: 2500 }] },
  { id: "c9", name: "Home & Kitchen", slug: "home-kitchen", icon: "cooking-pot", image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80", productCount: 16700, subcategories: [{ id: "sc9a", name: "Kitchen Appliances", slug: "kitchen-appliances", productCount: 5600 }, { id: "sc9b", name: "Home Decor", slug: "home-decor", productCount: 7200 }, { id: "sc9c", name: "Bedding", slug: "bedding", productCount: 3900 }] },
  { id: "c10", name: "Gaming", slug: "gaming", icon: "gamepad-2", image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&q=80", productCount: 5600, subcategories: [{ id: "sc10a", name: "Consoles", slug: "consoles", productCount: 1800 }, { id: "sc10b", name: "Games", slug: "games", productCount: 2400 }, { id: "sc10c", name: "Accessories", slug: "gaming-accessories", productCount: 1400 }] },
  { id: "c11", name: "Automotive", slug: "automotive", icon: "car", image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&q=80", productCount: 4200, subcategories: [{ id: "sc11a", name: "Car Electronics", slug: "car-electronics", productCount: 1500 }, { id: "sc11b", name: "Parts", slug: "car-parts", productCount: 1800 }, { id: "sc11c", name: "Accessories", slug: "car-accessories", productCount: 900 }] },
  { id: "c12", name: "Sports", slug: "sports", icon: "trophy", image: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=400&q=80", productCount: 6800, subcategories: [{ id: "sc12a", name: "Fitness", slug: "fitness", productCount: 2800 }, { id: "sc12b", name: "Outdoor", slug: "outdoor", productCount: 2200 }, { id: "sc12c", name: "Team Sports", slug: "team-sports", productCount: 1800 }] },
  { id: "c13", name: "Baby Products", slug: "baby-products", icon: "baby", image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&q=80", productCount: 5600, subcategories: [{ id: "sc13a", name: "Diapers", slug: "diapers", productCount: 1800 }, { id: "sc13b", name: "Toys", slug: "baby-toys", productCount: 2400 }, { id: "sc13c", name: "Clothing", slug: "baby-clothing", productCount: 1400 }] },
  { id: "c14", name: "Books", slug: "books", icon: "book-open", image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&q=80", productCount: 25400, subcategories: [{ id: "sc14a", name: "Fiction", slug: "fiction", productCount: 8900 }, { id: "sc14b", name: "Educational", slug: "educational", productCount: 9800 }, { id: "sc14c", name: "Children", slug: "children-books", productCount: 6700 }] },
  { id: "c15", name: "Health", slug: "health", icon: "heart-pulse", image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80", productCount: 5200, subcategories: [{ id: "sc15a", name: "Supplements", slug: "supplements", productCount: 2100 }, { id: "sc15b", name: "Medical", slug: "medical", productCount: 1700 }, { id: "sc15c", name: "Personal Care", slug: "personal-care", productCount: 1400 }] },
];

// ===== Sellers (Tanzanian Focus) =====
export const sellers: Seller[] = [
  { id: "s1", name: "James Ochieng", storeName: "TechHub Tanzania", logo: "https://api.dicebear.com/7.x/avataaars/svg?seed=James", banner: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200&q=80", description: "Premium electronics and gadgets from top brands.", rating: 4.8, totalSales: 15230, totalProducts: 342, followers: 12400, verified: true, joinedAt: "2022-03-15", responseRate: 98, responseTime: "< 1 hour", location: "Dar es Salaam, Tanzania", badges: ["Top Rated", "Fast Shipper", "Best Seller"] },
  { id: "s2", name: "Amina Hassan", storeName: "Fashion Forward TZ", logo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amina", banner: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200&q=80", description: "Curated fashion for the modern Tanzanian woman.", rating: 4.9, totalSales: 28400, totalProducts: 567, followers: 23100, verified: true, joinedAt: "2021-07-22", responseRate: 100, responseTime: "< 30 min", location: "Mwanza, Tanzania", badges: ["Top Rated", "Best Seller", "Fast Shipper"] },
  { id: "s3", name: "Peter Kamau", storeName: "Soko Gadgets", logo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Peter", banner: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1200&q=80", description: "Affordable tech accessories and mobile devices.", rating: 4.6, totalSales: 8900, totalProducts: 178, followers: 5600, verified: true, joinedAt: "2023-01-10", responseRate: 95, responseTime: "< 2 hours", location: "Arusha, Tanzania", badges: ["Top Rated"] },
  { id: "s4", name: "Grace Wanjiku", storeName: "Grace's Home Decor", logo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Grace", banner: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1200&q=80", description: "Beautiful home decor and furniture pieces.", rating: 4.7, totalSales: 12100, totalProducts: 256, followers: 8900, verified: true, joinedAt: "2022-09-05", responseRate: 97, responseTime: "< 1 hour", location: "Dodoma, Tanzania", badges: ["Top Rated", "Fast Shipper"] },
  { id: "s5", name: "David Mwangi", storeName: "SportZone TZ", logo: "https://api.dicebear.com/7.x/avataaars/svg?seed=David", banner: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=1200&q=80", description: "Everything sports and fitness equipment.", rating: 4.5, totalSales: 6700, totalProducts: 145, followers: 3400, verified: false, joinedAt: "2023-04-18", responseRate: 92, responseTime: "< 3 hours", location: "Mbeya, Tanzania", badges: [] },
  { id: "s6", name: "Sarah Akinyi", storeName: "Beauty & Glow TZ", logo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah", banner: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=1200&q=80", description: "Premium beauty products and cosmetics.", rating: 4.9, totalSales: 19800, totalProducts: 423, followers: 15600, verified: true, joinedAt: "2021-11-30", responseRate: 99, responseTime: "< 30 min", location: "Zanzibar, Tanzania", badges: ["Top Rated", "Best Seller"] },
  { id: "s7", name: "Joseph Mushi", storeName: "Mushi Fresh Groceries", logo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Joseph", banner: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80", description: "Fresh farm produce delivered to your door.", rating: 4.7, totalSales: 21300, totalProducts: 189, followers: 9800, verified: true, joinedAt: "2022-06-15", responseRate: 96, responseTime: "< 1 hour", location: "Morogoro, Tanzania", badges: ["Top Rated", "Fast Shipper"] },
  { id: "s8", name: "Rashid Salim", storeName: "Rashid Furniture", logo: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rashid", banner: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=80", description: "Handcrafted furniture made by Tanzanian artisans.", rating: 4.8, totalSales: 5600, totalProducts: 312, followers: 7200, verified: true, joinedAt: "2023-02-10", responseRate: 94, responseTime: "< 2 hours", location: "Tanga, Tanzania", badges: ["Top Rated"] },
];

// ===== Products (TZS Pricing) =====
export const products: Product[] = [
  { id: "p1", name: "iPhone 15 Pro Max 256GB", slug: "iphone-15-pro-max", description: "The most powerful iPhone ever. A17 Pro chip, 48MP camera system, and titanium design.", price: 3990000, discountPrice: 3490000, currency: "TZS", images: ["https://images.unsplash.com/photo-1696446701796-da61225697cc?w=600&q=80", "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80"], category: "Phones & Tablets", subcategory: "Smartphones", brand: "Apple", sku: "IP15PM256", quantity: 50, sold: 1280, condition: "new", colors: ["Natural Titanium", "Blue Titanium", "White Titanium"], tags: ["iphone", "apple", "smartphone", "premium"], seller: sellers[0], rating: 4.8, reviewCount: 342, warranty: "1 Year Apple Warranty", returnPolicy: "30-Day Return", status: "active", featured: true, trending: true, createdAt: "2024-01-15", updatedAt: "2024-03-01" },
  { id: "p2", name: "Samsung Galaxy S24 Ultra", slug: "samsung-s24-ultra", description: "Galaxy AI is here. Built with titanium, Galaxy S24 Ultra is a powerhouse of creativity and productivity.", price: 3500000, discountPrice: 2990000, currency: "TZS", images: ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80", "https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?w=600&q=80"], category: "Phones & Tablets", subcategory: "Smartphones", brand: "Samsung", sku: "SS24U256", quantity: 35, sold: 890, condition: "new", colors: ["Titanium Gray", "Titanium Violet", "Titanium Black"], tags: ["samsung", "galaxy", "smartphone", "android"], seller: sellers[0], rating: 4.7, reviewCount: 256, warranty: "1 Year Samsung Warranty", returnPolicy: "30-Day Return", status: "active", featured: true, trending: true, createdAt: "2024-02-01", updatedAt: "2024-03-01" },
  { id: "p3", name: "MacBook Pro 14\" M3 Pro", slug: "macbook-pro-14-m3", description: "Supercharged by M3 Pro chip. 18GB unified memory, 512GB SSD. Exceptional performance for pros.", price: 4990000, discountPrice: 4490000, currency: "TZS", images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80", "https://images.unsplash.com/photo-1611186871348-b1f696febbb3?w=600&q=80"], category: "Computers", subcategory: "Laptops", brand: "Apple", sku: "MBP14-M3-512", quantity: 25, sold: 560, condition: "new", tags: ["macbook", "apple", "laptop", "pro"], seller: sellers[0], rating: 4.9, reviewCount: 189, warranty: "1 Year Apple Warranty", returnPolicy: "30-Day Return", status: "active", featured: true, trending: false, createdAt: "2024-01-20", updatedAt: "2024-03-01" },
  { id: "p4", name: "Wireless Noise-Cancelling Headphones", slug: "wireless-nc-headphones", description: "Premium wireless headphones with active noise cancellation, 30-hour battery life, and crystal-clear sound.", price: 450000, discountPrice: 349000, currency: "TZS", images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80", "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80"], category: "Electronics", subcategory: "Audio", brand: "SoundMax", sku: "SM-NC-PRO", quantity: 200, sold: 3450, condition: "new", colors: ["Matte Black", "Silver", "Midnight Blue"], tags: ["headphones", "wireless", "noise-cancelling", "audio"], seller: sellers[2], rating: 4.6, reviewCount: 891, warranty: "2 Year Warranty", returnPolicy: "30-Day Return", status: "active", featured: true, trending: true, createdAt: "2024-01-10", updatedAt: "2024-02-15" },
  { id: "p5", name: "Premium Kitenge Maxi Dress", slug: "premium-kitenge-maxi-dress", description: "Stunning handcrafted Kitenge print maxi dress with modern silhouette. Perfect for weddings and special occasions.", price: 85000, discountPrice: 65000, currency: "TZS", images: ["https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&q=80"], category: "Fashion", subcategory: "Women", brand: "Fashion Forward TZ", sku: "KIT-MAXI-001", quantity: 150, sold: 2340, condition: "new", sizes: ["XS", "S", "M", "L", "XL", "XXL"], tags: ["kitenge", "african-print", "dress", "maxi", "tanzanian"], seller: sellers[1], rating: 4.9, reviewCount: 567, returnPolicy: "14-Day Return", status: "active", featured: true, trending: true, createdAt: "2024-02-15", updatedAt: "2024-03-01" },
  { id: "p6", name: "Smart Watch Series 9", slug: "smart-watch-series-9", description: "Advanced health monitoring, always-on display, and powerful performance in a sleek design.", price: 850000, discountPrice: 749000, currency: "TZS", images: ["https://images.unsplash.com/photo-1546868871-af0de0ae72e6?w=600&q=80", "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80"], category: "Electronics", subcategory: "Wearables", brand: "TechWear", sku: "TW-S9-BLK", quantity: 80, sold: 1560, condition: "new", colors: ["Midnight", "Starlight", "Product Red"], tags: ["smartwatch", "wearable", "fitness", "health"], seller: sellers[0], rating: 4.7, reviewCount: 432, warranty: "1 Year Warranty", returnPolicy: "30-Day Return", status: "active", featured: true, trending: true, createdAt: "2024-01-20", updatedAt: "2024-03-01" },
  { id: "p7", name: "Premium Leather Handbag", slug: "premium-leather-handbag", description: "Handcrafted genuine leather handbag with gold-tone hardware and spacious interior compartments. Made by Tanzanian artisans.", price: 350000, currency: "TZS", images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80", "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600&q=80"], category: "Fashion", subcategory: "Women", brand: "Luxe Craft TZ", sku: "LC-LHB-001", quantity: 45, sold: 890, condition: "new", colors: ["Tan", "Black", "Burgundy"], tags: ["leather", "handbag", "premium", "luxury", "tanzanian"], seller: sellers[1], rating: 4.8, reviewCount: 234, warranty: "1 Year Warranty", returnPolicy: "30-Day Return", status: "active", featured: false, trending: true, createdAt: "2024-02-10", updatedAt: "2024-03-01" },
  { id: "p8", name: "Samsung 65\" 4K Smart TV", slug: "samsung-65-4k-tv", description: "Crystal UHD 4K processor, HDR, smart TV with built-in streaming apps and voice control.", price: 2900000, discountPrice: 2490000, currency: "TZS", images: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80"], category: "Electronics", subcategory: "Smart Home", brand: "Samsung", sku: "SS-65-CU8000", quantity: 20, sold: 430, condition: "new", tags: ["tv", "samsung", "4k", "smart-tv"], seller: sellers[0], rating: 4.6, reviewCount: 312, warranty: "2 Year Warranty", returnPolicy: "30-Day Return", status: "active", featured: true, trending: false, createdAt: "2024-02-01", updatedAt: "2024-03-01" },
  { id: "p9", name: "Organic Skincare Bundle", slug: "organic-skincare-bundle", description: "Complete organic skincare routine with cleanser, toner, serum, and moisturizer. Natural Tanzanian ingredients.", price: 120000, discountPrice: 89000, currency: "TZS", images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80", "https://images.unsplash.com/photo-1570194065650-d99fb4b38c34?w=600&q=80"], category: "Beauty", subcategory: "Skincare", brand: "PureGlow TZ", sku: "PG-ORG-SET", quantity: 200, sold: 3450, condition: "new", tags: ["skincare", "organic", "natural", "beauty", "tanzanian"], seller: sellers[5], rating: 4.9, reviewCount: 1234, returnPolicy: "30-Day Return", status: "active", featured: true, trending: true, createdAt: "2024-02-20", updatedAt: "2024-03-01" },
  { id: "p10", name: "Ergonomic Office Chair", slug: "ergonomic-office-chair", description: "Premium ergonomic chair with lumbar support, adjustable armrests, and breathable mesh back.", price: 750000, discountPrice: 599000, currency: "TZS", images: ["https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80", "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600&q=80"], category: "Furniture", subcategory: "Office", brand: "Comfort Plus", sku: "CP-ERGO-001", quantity: 30, sold: 670, condition: "new", colors: ["Black", "Gray", "White"], tags: ["office", "ergonomic", "chair", "furniture"], seller: sellers[3], rating: 4.6, reviewCount: 345, warranty: "5 Year Warranty", returnPolicy: "60-Day Return", status: "active", featured: true, trending: false, createdAt: "2024-01-25", updatedAt: "2024-03-01" },
  { id: "p11", name: "Professional Running Shoes", slug: "professional-running-shoes", description: "Lightweight performance running shoes with responsive cushioning and breathable upper.", price: 250000, discountPrice: 189000, currency: "TZS", images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80"], category: "Shoes", subcategory: "Sneakers", brand: "SpeedRunner", sku: "SR-PRO-RUN", quantity: 100, sold: 2340, condition: "new", sizes: ["7", "8", "9", "10", "11", "12", "13"], colors: ["Black/White", "Blue/Neon", "Red/Black"], tags: ["running", "shoes", "sports", "fitness"], seller: sellers[4], rating: 4.5, reviewCount: 567, returnPolicy: "30-Day Return", status: "active", featured: false, trending: true, createdAt: "2024-02-05", updatedAt: "2024-03-01" },
  { id: "p12", name: "Fresh Organic Fruit Box", slug: "fresh-organic-fruit-box", description: "Weekly subscription box of fresh organic fruits sourced directly from Tanzanian farms.", price: 45000, discountPrice: 35000, currency: "TZS", images: ["https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&q=80", "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=600&q=80"], category: "Groceries", subcategory: "Fresh Food", brand: "Mushi Fresh", sku: "MF-ORG-001", quantity: 500, sold: 6780, condition: "new", tags: ["organic", "fruit", "fresh", "groceries", "tanzanian"], seller: sellers[6], rating: 4.7, reviewCount: 890, returnPolicy: "Same Day Return", status: "active", featured: true, trending: true, createdAt: "2024-02-10", updatedAt: "2024-03-01" },
  { id: "p13", name: "PS5 Pro Console", slug: "ps5-pro-console", description: "PlayStation 5 Pro with 2TB SSD, ray tracing, and up to 8K output. The ultimate gaming experience.", price: 1800000, currency: "TZS", images: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&q=80", "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80"], category: "Gaming", subcategory: "Consoles", brand: "Sony", sku: "PS5-PRO-2TB", quantity: 15, sold: 380, condition: "new", tags: ["playstation", "ps5", "gaming", "console"], seller: sellers[2], rating: 4.8, reviewCount: 234, warranty: "1 Year Warranty", returnPolicy: "30-Day Return", status: "active", featured: true, trending: true, createdAt: "2024-02-25", updatedAt: "2024-03-01" },
  { id: "p14", name: "Handcrafted Mpingo Wood Sculpture", slug: "mpingo-wood-sculpture", description: "Beautiful hand-carved sculpture made from premium Tanzanian Mpingo (ebony) wood by master artisans.", price: 280000, currency: "TZS", images: ["https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=600&q=80"], category: "Home & Kitchen", subcategory: "Home Decor", brand: "TZ Artisans", sku: "MP-WOOD-001", quantity: 25, sold: 340, condition: "new", tags: ["handcrafted", "mpingo", "wood", "tanzanian", "art"], seller: sellers[7], rating: 4.9, reviewCount: 156, returnPolicy: "14-Day Return", status: "active", featured: false, trending: true, createdAt: "2024-01-05", updatedAt: "2024-02-20" },
  { id: "p15", name: "AirPods Pro 2nd Gen", slug: "airpods-pro-2", description: "Adaptive audio, active noise cancellation, and personalized spatial audio. USB-C charging case.", price: 450000, discountPrice: 399000, currency: "TZS", images: ["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&q=80", "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=600&q=80"], category: "Electronics", subcategory: "Audio", brand: "Apple", sku: "APP-AIRPODS-P2", quantity: 120, sold: 2100, condition: "new", tags: ["airpods", "apple", "earphones", "wireless", "audio"], seller: sellers[0], rating: 4.7, reviewCount: 678, warranty: "1 Year Warranty", returnPolicy: "30-Day Return", status: "active", featured: true, trending: true, createdAt: "2024-01-10", updatedAt: "2024-03-01" },
  { id: "p16", name: "Tanzanian Coffee Gift Set", slug: "tanzanian-coffee-set", description: "Premium Arabica coffee beans from Kilimanjaro region. Includes a French press and 3 blends.", price: 65000, discountPrice: 49000, currency: "TZS", images: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80"], category: "Groceries", subcategory: "Beverages", brand: "Kilimanjaro Coffee", sku: "KILI-COF-001", quantity: 300, sold: 4560, condition: "new", tags: ["coffee", "tanzanian", "kilimanjaro", "arabica", "gift"], seller: sellers[6], rating: 4.8, reviewCount: 734, returnPolicy: "14-Day Return", status: "active", featured: true, trending: true, createdAt: "2024-02-01", updatedAt: "2024-03-01" },
];

// ===== Flash Sale =====
export const flashSale: FlashSale = {
  id: "fs1",
  title: "Flash Sale",
  description: "Limited time offers - up to 60% off on selected items!",
  products: products.slice(0, 6),
  startTime: new Date().toISOString(),
  endTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  discount: 60,
  isActive: true,
};

// ===== Banners =====
export const banners: Banner[] = [
  { id: "b1", title: "Premium Tech Deals", subtitle: "Up to 40% off", description: "Latest smartphones, laptops and gadgets at unbeatable prices", cta: "Shop Now", link: "/marketplace?category=electronics", desktopImage: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1920&q=80", mobileImage: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=600&q=80", badge: "Limited Time", discount: 40, type: "hero", priority: 1, isActive: true, startDate: new Date().toISOString(), endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(), bgColor: "from-blue-600 to-blue-900" },
  { id: "b2", title: "Tanzanian Fashion Week", subtitle: "New Collection", description: "Discover authentic Tanzanian fashion from top local designers", cta: "Explore Fashion", link: "/marketplace?category=fashion", desktopImage: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1920&q=80", mobileImage: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&q=80", badge: "New", discount: 25, type: "category", priority: 2, isActive: true, startDate: new Date().toISOString(), endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(), bgColor: "from-rose-600 to-rose-900" },
  { id: "b3", title: "Free Delivery Week", subtitle: "Nationwide", description: "Enjoy free delivery on all orders across Tanzania mainland and Zanzibar", cta: "Start Shopping", link: "/marketplace", desktopImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1920&q=80", mobileImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80", badge: "Special Offer", type: "promotional", priority: 3, isActive: true, startDate: new Date().toISOString(), endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), bgColor: "from-emerald-600 to-emerald-900" },
];

// ===== Reviews =====
export const reviews: Review[] = [
  { id: "r1", userId: "u1", userName: "John M.", userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John", productId: "p1", rating: 5, title: "Absolutely amazing!", comment: "Best phone I've ever owned. The camera is incredible and battery life is outstanding.", likes: 24, createdAt: "2024-02-15" },
  { id: "r2", userId: "u2", userName: "Mary W.", userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mary", productId: "p1", rating: 4, title: "Great phone, great price", comment: "Loving the phone so far. The titanium design feels premium.", likes: 12, createdAt: "2024-02-20" },
  { id: "r3", userId: "u3", userName: "Amina K.", userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AminaK", productId: "p5", rating: 5, title: "Stunning dress!", comment: "Wore this to my sister's wedding and got so many compliments. The quality is amazing!", likes: 45, createdAt: "2024-02-18" },
  { id: "r4", userId: "u4", userName: "David S.", userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DavidS", productId: "p9", rating: 5, title: "My skin has never looked better", comment: "After using this bundle for 2 weeks, my skin is glowing. Love the natural ingredients!", likes: 33, createdAt: "2024-02-22" },
];

// ===== Testimonials =====
export const testimonials: Testimonial[] = [
  { id: "t1", name: "Elizabeth Njoroge", role: "Fashion Buyer, Dar es Salaam", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elizabeth", content: "SokoDigital has transformed how I shop for fashion. The variety of sellers and authentic products is unmatched. I've discovered so many amazing Tanzanian brands!", rating: 5 },
  { id: "t2", name: "Michael Omondi", role: "Electronics Enthusiast, Arusha", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael", content: "Found the best deals on electronics here. The seller verification system gives me confidence, and delivery is always on time. Highly recommended!", rating: 5 },
  { id: "t3", name: "Sarah Kimani", role: "Home Decor Lover, Mwanza", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahK", content: "The AI recommendations helped me find exactly what I needed for my new home. Beautiful products, great prices, and excellent customer service.", rating: 4 },
  { id: "t4", name: "David Mushi", role: "Tech Seller, Mbeya", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DavidM", content: "As a seller, SokoDigital has been a game-changer. The analytics tools and seller dashboard make managing my store effortless. Sales have increased 3x!", rating: 5 },
  { id: "t5", name: "Grace Hassan", role: "Loyal Customer, Zanzibar", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=GraceH", content: "Free delivery is a game changer! I order groceries every week and they arrive fresh. SokoDigital is the best thing to happen to Tanzanian e-commerce.", rating: 5 },
  { id: "t6", name: "Joseph Mbwana", role: "Small Business Owner, Dodoma", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JosephM", content: "Selling on SokoDigital helped me grow my furniture business to reach customers across Tanzania. The platform is easy to use and the support team is amazing.", rating: 5 },
];

// ===== Stats =====
export const stats: Stat[] = [
  { value: "2.5M+", label: "Active Buyers", icon: "users", suffix: "+12%" },
  { value: "50K+", label: "Verified Sellers", icon: "store", suffix: "+8%" },
  { value: "5M+", label: "Products Listed", icon: "package", suffix: "+15%" },
  { value: "98%", label: "Satisfaction Rate", icon: "smile", suffix: "+2%" },
];

// ===== Notifications =====
export const notifications: Notification[] = [
  { id: "n1", type: "order", title: "Order Confirmed", message: "Your order #ORD-2024-001 has been confirmed and is being processed.", read: false, link: "/orders/ord-001", createdAt: new Date().toISOString() },
  { id: "n2", type: "promotion", title: "Flash Sale Alert!", message: "Up to 60% off on electronics - don't miss out!", read: false, link: "/flash-sale", createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: "n3", type: "system", title: "Welcome to SokoDigital", message: "Thank you for joining! Complete your profile to get started.", read: true, link: "/profile", createdAt: new Date(Date.now() - 86400000).toISOString() },
  { id: "n4", type: "message", title: "New message from TechHub Tanzania", message: "Your inquiry about iPhone 15 Pro Max has been answered.", read: false, link: "/messages", createdAt: new Date(Date.now() - 7200000).toISOString() },
];

// ===== AI Suggestions =====
export const aiSuggestions: AISuggestion[] = [
  { id: "as1", text: "Find a laptop under 500,000 TZS", icon: "search", category: "shopping" },
  { id: "as2", text: "Recommend a good smartphone", icon: "smartphone", category: "shopping" },
  { id: "as3", text: "Compare prices on iPhones", icon: "search", category: "shopping" },
  { id: "as4", text: "Find cheaper alternatives", icon: "trending-down", category: "shopping" },
  { id: "as5", text: "Suggest beauty products for dry skin", icon: "sparkles", category: "shopping" },
  { id: "as6", text: "What are today's best deals?", icon: "zap", category: "deals" },
];

// ===== Trending Search Terms =====
export const trendingSearches = [
  "iPhone 15", "Kitenge dresses", "Laptop deals", "Smart watches",
  "Coffee gift set", "Furniture", "Skincare", "Sneakers"
];

// ===== Payment Methods (Tanzanian) =====
export const paymentMethods = [
  { id: "mpesa", name: "M-Pesa", icon: "smartphone", description: "Pay with M-Pesa mobile money" },
  { id: "airtel", name: "Airtel Money", icon: "smartphone", description: "Pay with Airtel Money" },
  { id: "mixx", name: "Mixx by Yas", icon: "smartphone", description: "Pay with Mixx by Yas" },
  { id: "halopesa", name: "HaloPesa", icon: "smartphone", description: "Pay with HaloPesa" },
  { id: "crdb", name: "CRDB Bank", icon: "landmark", description: "Pay with CRDB Bank" },
  { id: "nmb", name: "NMB Bank", icon: "landmark", description: "Pay with NMB Bank" },
  { id: "nbc", name: "NBC Bank", icon: "landmark", description: "Pay with NBC Bank" },
  { id: "visa", name: "Visa", icon: "credit-card", description: "Pay with Visa card" },
  { id: "mastercard", name: "Mastercard", icon: "credit-card", description: "Pay with Mastercard" },
];

// ===== Footer Links =====
export const footerLinks = {
  "Shop": ["Phones & Tablets", "Computers", "Electronics", "Fashion", "Shoes", "Beauty", "Groceries", "Furniture", "Home & Kitchen", "Gaming", "Sports", "Books", "Health"],
  "For Sellers": ["Start Selling", "Seller Dashboard", "Seller Academy", "Fees & Pricing", "Seller Community", "Success Stories", "Marketing Tools"],
  "Customer Service": ["Help Center", "Returns & Refunds", "Shipping Info", "Order Tracking", "Contact Us", "FAQs", "Report a Problem"],
  "About SokoDigital": ["About Us", "Careers", "Press & Media", "Blog", "Investors", "Privacy Policy", "Terms of Service", "Cookie Policy"],
};
