import type {
  Product, Seller, Category, FlashSale, Review, Notification,
  Testimonial, Stat, Banner, AISuggestion
} from "@/types";
import banner1Img from "@/assets/banner1.png";
import banner2Img from "@/assets/banner2.png";
import banner3Img from "@/assets/banner3.png";
import banner4Img from "@/assets/banner4.png";
import banner5Img from "@/assets/banner5.png";

// ===== Marketplace Stats =====
export const stats: Stat[] = [
  { value: "50K+", label: "Active Buyers", icon: "Users" },
  { value: "10K+", label: "Trusted Sellers", icon: "Store" },
  { value: "100K+", label: "Products Listed", icon: "Package" },
  { value: "1M+", label: "Orders Delivered", icon: "ShoppingCart" },
];

// ===== Categories =====
export const categories: Category[] = [
  { id: "cat-1", name: "Phones & Tablets", slug: "phones-tablets", icon: "Smartphone", image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&q=80", productCount: 15230, subcategories: [
    { id: "sub-1", name: "Smartphones", slug: "smartphones", productCount: 8500 },
    { id: "sub-2", name: "Tablets", slug: "tablets", productCount: 3200 },
    { id: "sub-3", name: "Accessories", slug: "phone-accessories", productCount: 3530 },
  ]},
  { id: "cat-2", name: "Computers", slug: "computers", icon: "Monitor", image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80", productCount: 8940, subcategories: [
    { id: "sub-4", name: "Laptops", slug: "laptops", productCount: 4500 },
    { id: "sub-5", name: "Desktops", slug: "desktops", productCount: 2100 },
    { id: "sub-6", name: "Computer Parts", slug: "computer-parts", productCount: 2340 },
  ]},
  { id: "cat-3", name: "Electronics", slug: "electronics", icon: "Zap", image: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=400&q=80", productCount: 12450 },
  { id: "cat-4", name: "Fashion", slug: "fashion", icon: "Shirt", image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&q=80", productCount: 28400 },
  { id: "cat-5", name: "Shoes", slug: "shoes", icon: "Footprints", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80", productCount: 12300 },
  { id: "cat-6", name: "Beauty", slug: "beauty", icon: "Sparkles", image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&q=80", productCount: 9800 },
  { id: "cat-7", name: "Groceries", slug: "groceries", icon: "Apple", image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&q=80", productCount: 45000 },
  { id: "cat-8", name: "Furniture", slug: "furniture", icon: "Armchair", image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80", productCount: 6700 },
  { id: "cat-9", name: "Home & Kitchen", slug: "home-kitchen", icon: "Home", image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80", productCount: 15600 },
  { id: "cat-10", name: "Gaming", slug: "gaming", icon: "Gamepad2", image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=400&q=80", productCount: 4300 },
  { id: "cat-11", name: "Automotive", slug: "automotive", icon: "Car", image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&q=80", productCount: 3400 },
  { id: "cat-12", name: "Sports", slug: "sports", icon: "Trophy", image: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=400&q=80", productCount: 5600 },
  { id: "cat-13", name: "Baby Products", slug: "baby-products", icon: "Baby", image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&q=80", productCount: 2900 },
  { id: "cat-14", name: "Books", slug: "books", icon: "BookOpen", image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&q=80", productCount: 8700 },
  { id: "cat-15", name: "Health", slug: "health", icon: "Heart", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80", productCount: 6200 },
];

// ===== Sellers =====
export const sellers: Seller[] = [
  { id: "seller-1", name: "Amina Juma", storeName: "Amina Fashion House",
    logo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    banner: "https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Premium Tanzanian fashion and accessories. Handmade with love.", rating: 4.8,
    totalSales: 15230, totalProducts: 340, followers: 12500, verified: true,
    joinedAt: "2023-01-15", responseRate: 98, responseTime: "within 1 hour", location: "Dar es Salaam",
    badges: ["Top Seller", "Fast Shipper", "Quality Assured"] },
  { id: "seller-2", name: "James Ochieng", storeName: "TechZone Tanzania",
    logo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    banner: "https://images.pexels.com/photos/325153/pexels-photo-325153.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Your trusted source for authentic electronics and gadgets.", rating: 4.6,
    totalSales: 8940, totalProducts: 520, followers: 8900, verified: true,
    joinedAt: "2023-03-20", responseRate: 95, responseTime: "within 2 hours", location: "Arusha",
    badges: ["Verified", "Top Rated"] },
  { id: "seller-3", name: "Mwanahamisi Salim", storeName: "Mama's Fresh Groceries",
    logo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    banner: "https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Fresh farm produce delivered to your doorstep daily.", rating: 4.9,
    totalSales: 28400, totalProducts: 180, followers: 18400, verified: true,
    joinedAt: "2023-02-01", responseRate: 99, responseTime: "within 30 mins", location: "Zanzibar",
    badges: ["Top Seller", "Fresh Guarantee", "Best Price"] },
  { id: "seller-4", name: "Raj Patel", storeName: "Furniture Palace",
    logo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    banner: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Modern and traditional furniture for every home.", rating: 4.5,
    totalSales: 4300, totalProducts: 260, followers: 5600, verified: true,
    joinedAt: "2023-06-10", responseRate: 92, responseTime: "within 3 hours", location: "Mwanza",
    badges: ["Quality Assured", "Free Delivery"] },
  { id: "seller-5", name: "Grace Mwangi", storeName: "Grace Beauty Store",
    logo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80",
    banner: "https://images.pexels.com/photos/2113855/pexels-photo-2113855.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Premium beauty and skincare products from around the world.", rating: 4.7,
    totalSales: 12300, totalProducts: 450, followers: 10200, verified: true,
    joinedAt: "2023-04-05", responseRate: 96, responseTime: "within 1 hour", location: "Dodoma",
    badges: ["Verified", "Top Rated", "Fast Shipper"] },
  { id: "seller-6", name: "Peter Kimani", storeName: "SportZone TZ",
    logo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    banner: "https://images.pexels.com/photos/2294361/pexels-photo-2294361.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Premium sports equipment, athletic wear, and fitness gear.", rating: 4.4,
    totalSales: 6700, totalProducts: 190, followers: 4800, verified: true,
    joinedAt: "2023-08-15", responseRate: 93, responseTime: "within 2 hours", location: "Mbeya",
    badges: ["Verified", "Fast Shipper"] },
  { id: "seller-7", name: "Hannah Mtui", storeName: "Home Essentials TZ",
    logo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    banner: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Quality home and kitchen essentials for modern Tanzanian homes.", rating: 4.6,
    totalSales: 9200, totalProducts: 310, followers: 7200, verified: true,
    joinedAt: "2023-05-01", responseRate: 97, responseTime: "within 1 hour", location: "Morogoro",
    badges: ["Quality Assured", "Top Rated"] },
  { id: "seller-8", name: "John Mbwana", storeName: "BookWorm Tanzania",
    logo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    banner: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=1200",
    description: "Books, stationery, and educational materials for all ages.", rating: 4.5,
    totalSales: 5400, totalProducts: 1200, followers: 3900, verified: true,
    joinedAt: "2023-09-10", responseRate: 94, responseTime: "within 3 hours", location: "Arusha",
    badges: ["Verified", "Fast Shipper"] },
];

// ===== Products =====
export const products: Product[] = [
  { id: "p1", name: "iPhone 15 Pro Max 256GB", slug: "iphone-15-pro-max-256gb",
    description: "The most powerful iPhone ever. A17 Pro chip, 48MP camera system, and all-day battery life.",
    price: 3500000, discountPrice: 3150000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1696446701796-da61225697cc?w=600&q=80","https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80","https://images.unsplash.com/photo-1695149721801-4c9aa8c2e4b8?w=600&q=80"],
    category: "Phones & Tablets", brand: "Apple", sku: "IP15PM256", quantity: 50, sold: 230, condition: "new",
    specifications: { "Display": "6.7-inch OLED", "Chip": "A17 Pro", "Camera": "48MP Triple", "Battery": "4422mAh" },
    colors: ["Natural Titanium", "Blue Titanium", "White Titanium"],
    tags: ["iphone", "apple", "premium", "smartphone"],
    seller: sellers[0], rating: 4.8, reviewCount: 234, warranty: "1 Year Apple Warranty", returnPolicy: "14 days return",
    deliveryOptions: [{ method: "Standard", price: 15000, estimatedDays: "2-3 days" },{ method: "Express", price: 35000, estimatedDays: "1 day" }],
    featured: true, trending: false, status: "active", createdAt: "2024-01-15", updatedAt: "2024-02-01" },
  { id: "p2", name: "MacBook Pro 16-inch M3 Max", slug: "macbook-pro-16-m3-max",
    description: "Supercharged by M3 Max chip. Up to 128GB unified memory. Stunning 16-inch Liquid Retina XDR display.",
    price: 5800000, discountPrice: 5490000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80","https://images.unsplash.com/photo-1611186871348-b1f696febbb3?w=600&q=80"],
    category: "Computers", brand: "Apple", sku: "MBP16M3M", quantity: 25, sold: 89, condition: "new",
    specifications: { "Chip": "M3 Max", "RAM": "48GB", "Storage": "1TB SSD", "Display": "16.2-inch" },
    tags: ["macbook", "apple", "laptop", "premium"],
    seller: sellers[1], rating: 4.9, reviewCount: 156, warranty: "1 Year Apple Warranty",
    deliveryOptions: [{ method: "Standard", price: 20000, estimatedDays: "2-3 days" },{ method: "Express", price: 45000, estimatedDays: "1 day" }],
    featured: true, trending: true, status: "active", createdAt: "2024-01-20", updatedAt: "2024-02-01" },
  { id: "p3", name: "Sony WH-1000XM5 Wireless Headphones", slug: "sony-wh-1000xm5",
    description: "Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling.",
    price: 650000, discountPrice: 520000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80","https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80"],
    category: "Electronics", brand: "Sony", sku: "WH1000XM5", quantity: 100, sold: 445, condition: "new",
    specifications: { "Type": "Over-ear", "Battery": "30 hours", "Noise Cancellation": "Adaptive", "Codec": "LDAC" },
    colors: ["Black", "Silver", "Midnight Blue"],
    tags: ["sony", "headphones", "noise-cancelling", "wireless"],
    seller: sellers[1], rating: 4.7, reviewCount: 312, warranty: "1 Year Sony Warranty", returnPolicy: "7 days return",
    deliveryOptions: [{ method: "Standard", price: 8000, estimatedDays: "1-2 days" },{ method: "Express", price: 15000, estimatedDays: "Same day" }],
    featured: true, trending: false, status: "active", createdAt: "2024-01-10", updatedAt: "2024-02-01" },
  { id: "p4", name: "Apple Watch Ultra 2", slug: "apple-watch-ultra-2",
    description: "Most rugged and capable Apple Watch. 49mm titanium case, precision dual-frequency GPS.",
    price: 1850000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1546868871-af0de0ae72e6?w=600&q=80","https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80"],
    category: "Electronics", brand: "Apple", sku: "AWU2", quantity: 40, sold: 167, condition: "new",
    specifications: { "Display": "49mm", "Chip": "S9 SiP", "Battery": "36 hours", "Water Resistance": "100m" },
    colors: ["Natural Titanium", "Black Titanium"],
    tags: ["apple", "watch", "premium", "fitness"],
    seller: sellers[0], rating: 4.8, reviewCount: 89, warranty: "1 Year Apple Warranty",
    deliveryOptions: [{ method: "Standard", price: 10000, estimatedDays: "1-2 days" },{ method: "Express", price: 20000, estimatedDays: "Same day" }],
    featured: true, trending: false, status: "active", createdAt: "2024-01-25", updatedAt: "2024-02-01" },
  { id: "p5", name: "Nike Air Max 270 React", slug: "nike-air-max-270-react",
    description: "Comfort meets style. Dual-pressure Air Max unit and React foam for all-day comfort.",
    price: 280000, discountPrice: 210000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80","https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80"],
    category: "Shoes", brand: "Nike", sku: "AM270R", quantity: 200, sold: 890, condition: "new",
    specifications: { "Type": "Casual", "Material": "Mesh/Synthetic", "Sole": "Rubber" },
    colors: ["Black/White", "Blue/Orange", "All White"], sizes: ["39", "40", "41", "42", "43", "44", "45"],
    tags: ["nike", "shoes", "sneakers", "fashion"],
    seller: sellers[0], rating: 4.6, reviewCount: 567, returnPolicy: "30 days return",
    deliveryOptions: [{ method: "Standard", price: 7000, estimatedDays: "1-3 days" },{ method: "Express", price: 12000, estimatedDays: "1 day" }],
    featured: false, trending: true, status: "active", createdAt: "2024-01-05", updatedAt: "2024-02-01" },
  { id: "p6", name: "Premium Leather Handbag", slug: "premium-leather-handbag",
    description: "Handcrafted genuine leather handbag. Perfect for work and special occasions.",
    price: 350000, discountPrice: 280000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80","https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600&q=80"],
    category: "Fashion", brand: "Local Artisan", sku: "LBH001", quantity: 30, sold: 145, condition: "new",
    specifications: { "Material": "Genuine Leather", "Color": "Brown", "Dimensions": "30x25x10cm" },
    colors: ["Brown", "Black", "Tan"],
    tags: ["handbag", "leather", "premium", "fashion"],
    seller: sellers[0], rating: 4.9, reviewCount: 78, returnPolicy: "14 days return",
    deliveryOptions: [{ method: "Standard", price: 8000, estimatedDays: "1-2 days" }],
    featured: false, trending: true, status: "active", createdAt: "2024-02-01", updatedAt: "2024-02-01" },
  { id: "p7", name: "Samsung 65-inch OLED 4K TV", slug: "samsung-65-oled-4k-tv",
    description: "Stunning OLED display with quantum dot technology. Dolby Atmos and Dolby Vision.",
    price: 4200000, discountPrice: 3800000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80","https://images.unsplash.com/photo-1601944179066-29786cb9d32a?w=600&q=80"],
    category: "Electronics", brand: "Samsung", sku: "S65OLED", quantity: 15, sold: 67, condition: "new",
    specifications: { "Display": "65-inch OLED", "Resolution": "4K UHD", "Smart TV": "Tizen OS", "Audio": "Dolby Atmos" },
    tags: ["samsung", "tv", "oled", "4k", "home-theater"],
    seller: sellers[1], rating: 4.7, reviewCount: 98, warranty: "2 Year Samsung Warranty",
    deliveryOptions: [{ method: "Standard", price: 50000, estimatedDays: "3-5 days" },{ method: "Express", price: 80000, estimatedDays: "1-2 days" }],
    featured: false, trending: false, status: "active", createdAt: "2024-01-18", updatedAt: "2024-02-01" },
  { id: "p8", name: "DJI Mini 4 Pro Drone", slug: "dji-mini-4-pro",
    description: "Under 249g. 4K/100fps video. Omnidirectional obstacle sensing. 34-min flight time.",
    price: 2400000, discountPrice: 2150000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?w=600&q=80","https://images.unsplash.com/photo-1579829366248-204fe8413f31?w=600&q=80"],
    category: "Electronics", brand: "DJI", sku: "DJIM4P", quantity: 20, sold: 56, condition: "new",
    specifications: { "Weight": "249g", "Camera": "4K/100fps", "Flight Time": "34 min", "Range": "20km" },
    tags: ["dji", "drone", "camera", "gadget"],
    seller: sellers[1], rating: 4.8, reviewCount: 45, warranty: "1 Year DJI Warranty",
    deliveryOptions: [{ method: "Standard", price: 15000, estimatedDays: "2-3 days" },{ method: "Express", price: 35000, estimatedDays: "1 day" }],
    featured: false, trending: true, status: "active", createdAt: "2024-02-01", updatedAt: "2024-02-01" },
  { id: "p9", name: "Samsung Galaxy S24 Ultra 512GB", slug: "samsung-galaxy-s24-ultra",
    description: "Galaxy AI is here. Built with premium titanium, Galaxy S24 Ultra features a flat display, a long-lasting battery, and a powerful processor.",
    price: 2800000, discountPrice: 2450000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1712957393402-5e708829132c?w=600&q=80","https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=80"],
    category: "Phones & Tablets", brand: "Samsung", sku: "S24U512", quantity: 35, sold: 180, condition: "new",
    specifications: { "Display": "6.8-inch Dynamic AMOLED", "Chip": "Snapdragon 8 Gen 3", "Camera": "200MP", "Battery": "5000mAh" },
    colors: ["Titanium Gray", "Titanium Violet", "Titanium Black"],
    tags: ["samsung", "galaxy", "android", "smartphone"],
    seller: sellers[1], rating: 4.7, reviewCount: 198, warranty: "1 Year Samsung Warranty", returnPolicy: "14 days return",
    deliveryOptions: [{ method: "Standard", price: 15000, estimatedDays: "2-3 days" },{ method: "Express", price: 35000, estimatedDays: "1 day" }],
    featured: true, trending: true, status: "active", createdAt: "2024-02-15", updatedAt: "2024-03-01" },
  { id: "p10", name: "Adidas Ultraboost Light Running Shoes", slug: "adidas-ultraboost-light",
    description: "The lightest Ultraboost ever. Featuring new Light BOOST midsole for incredible energy return with every step.",
    price: 320000, discountPrice: 260000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80","https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80"],
    category: "Shoes", brand: "Adidas", sku: "UBLIGHT", quantity: 85, sold: 340, condition: "new",
    specifications: { "Type": "Running", "Material": "Mesh/Knit", "Sole": "Light BOOST", "Weight": "290g" },
    colors: ["Core Black", "Cloud White", "Grey"], sizes: ["39", "40", "41", "42", "43", "44"],
    tags: ["adidas", "running", "shoes", "sneakers"],
    seller: sellers[0], rating: 4.5, reviewCount: 234, returnPolicy: "30 days return",
    deliveryOptions: [{ method: "Standard", price: 7000, estimatedDays: "1-3 days" }],
    featured: false, trending: true, status: "active", createdAt: "2024-02-10", updatedAt: "2024-03-01" },
  { id: "p11", name: "Kitenge African Print Dress", slug: "kitenge-african-print-dress",
    description: "Beautiful handcrafted Kitenge dress made from authentic African wax print fabric. Perfect for weddings, parties, and special occasions.",
    price: 85000, discountPrice: 76000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80","https://images.unsplash.com/photo-1550639525-c97d455acf70?w=600&q=80"],
    category: "Fashion", brand: "Local Artisan", sku: "KTG001", quantity: 50, sold: 420, condition: "new",
    specifications: { "Material": "100% Cotton Wax Print", "Length": "Midi", "Care": "Hand wash cold" },
    sizes: ["S", "M", "L", "XL", "2XL"],
    tags: ["kitenge", "african", "fashion", "dress", "tanzania"],
    seller: sellers[0], rating: 4.8, reviewCount: 156, returnPolicy: "7 days return",
    deliveryOptions: [{ method: "Standard", price: 5000, estimatedDays: "1-2 days" }],
    featured: true, trending: true, status: "active", createdAt: "2024-01-20", updatedAt: "2024-02-01" },
  { id: "p12", name: "Professional Soccer Ball - Size 5", slug: "professional-soccer-ball",
    description: "FIFA Quality Pro certified match ball. Machine-stitched TPU casing with butyl bladder for excellent air retention.",
    price: 95000, discountPrice: 78000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1614632537423-0e3ff22d1a7e?w=600&q=80","https://images.unsplash.com/photo-1575361204480-a4a5b3e1a0c9?w=600&q=80"],
    category: "Sports", brand: "Adidas", sku: "SPRT001", quantity: 120, sold: 580, condition: "new",
    specifications: { "Size": "5 (Standard)", "Material": "TPU", "Bladder": "Butyl", "Certification": "FIFA Quality Pro" },
    tags: ["soccer", "football", "sports", "ball"],
    seller: sellers[5], rating: 4.4, reviewCount: 89, returnPolicy: "7 days return",
    deliveryOptions: [{ method: "Standard", price: 5000, estimatedDays: "1-3 days" }],
    featured: false, trending: false, status: "active", createdAt: "2024-02-05", updatedAt: "2024-03-01" },
  { id: "p13", name: "Non-Stick Cookware Set 8-Piece", slug: "non-stick-cookware-set",
    description: "Premium non-stick cookware set including pots, pans, and utensils. Suitable for all hob types including induction.",
    price: 450000, discountPrice: 380000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80","https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&q=80"],
    category: "Home & Kitchen", brand: "Local Brand", sku: "KITCHEN8", quantity: 45, sold: 230, condition: "new",
    specifications: { "Pieces": "8", "Material": "Aluminum + Non-stick coating", "Dishwasher Safe": "Yes", "Oven Safe": "Up to 180°C" },
    tags: ["kitchen", "cookware", "home", "non-stick"],
    seller: sellers[6], rating: 4.6, reviewCount: 134, warranty: "2 Year Warranty", returnPolicy: "14 days return",
    deliveryOptions: [{ method: "Standard", price: 12000, estimatedDays: "2-4 days" }],
    featured: true, trending: false, status: "active", createdAt: "2024-01-10", updatedAt: "2024-02-01" },
  { id: "p14", name: "Gaming Chair with Footrest", slug: "gaming-chair-with-footrest",
    description: "Ergonomic gaming chair with adjustable lumbar support, 4D armrests, retractable footrest, and premium PU leather.",
    price: 650000, discountPrice: 550000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600&q=80","https://images.unsplash.com/photo-1616587894289-86480e533129?w=600&q=80"],
    category: "Gaming", brand: "GamerPro", sku: "GCH001", quantity: 25, sold: 89, condition: "new",
    specifications: { "Material": "PU Leather", "Weight Capacity": "150kg", "Armrests": "4D", "Footrest": "Retractable" },
    colors: ["Black/Red", "Black/Blue", "All Black"],
    tags: ["gaming", "chair", "furniture", "ergonomic"],
    seller: sellers[1], rating: 4.5, reviewCount: 67, warranty: "1 Year Warranty",
    deliveryOptions: [{ method: "Standard", price: 25000, estimatedDays: "3-5 days" }],
    featured: false, trending: true, status: "active", createdAt: "2024-02-20", updatedAt: "2024-03-01" },
  { id: "p15", name: "Organic Green Tea Collection - 12 Boxes", slug: "organic-green-tea-collection",
    description: "Premium organic green tea sourced from the Usambara mountains. Rich in antioxidants, naturally caffeine-free options available.",
    price: 45000, discountPrice: 38000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80","https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80"],
    category: "Groceries", brand: "Usambara Tea Co.", sku: "TEABOX12", quantity: 200, sold: 1200, condition: "new",
    specifications: { "Type": "Green Tea", "Quantity": "12 boxes (20 bags each)", "Origin": "Usambara Mountains, Tanzania", "Organic": "Certified Organic" },
    tags: ["tea", "organic", "groceries", "health"],
    seller: sellers[2], rating: 4.7, reviewCount: 445,
    deliveryOptions: [{ method: "Standard", price: 3000, estimatedDays: "1-2 days" }],
    featured: false, trending: true, status: "active", createdAt: "2024-01-01", updatedAt: "2024-03-01" },
  { id: "p16", name: "Car Dashboard Camera HD 4K", slug: "car-dashboard-camera-4k",
    description: "Ultra HD 4K dash cam with night vision, wide-angle lens, GPS tracking, and parking mode for complete driving peace of mind.",
    price: 210000, discountPrice: 175000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&q=80","https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&q=80"],
    category: "Automotive", brand: "AutoGuard", sku: "DASH4K", quantity: 60, sold: 190, condition: "new",
    specifications: { "Resolution": "4K (3840x2160)", "Night Vision": "Yes", "GPS": "Built-in", "Parking Mode": "Yes" },
    tags: ["automotive", "dashcam", "car", "safety"],
    seller: sellers[5], rating: 4.3, reviewCount: 78, warranty: "1 Year Warranty", returnPolicy: "14 days return",
    deliveryOptions: [{ method: "Standard", price: 8000, estimatedDays: "2-3 days" }],
    featured: false, trending: false, status: "active", createdAt: "2024-02-15", updatedAt: "2024-03-01" },
  { id: "p17", name: "Wireless Noise-Canceling Earbuds Pro", slug: "wireless-earbuds-pro",
    description: "Premium true wireless earbuds with active noise cancellation, 30h battery life, and IPX5 waterproof rating.",
    price: 180000, discountPrice: 145000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=600&q=80","https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=600&q=80"],
    category: "Electronics", brand: "SoundPro", sku: "WEP001", quantity: 120, sold: 670, condition: "new",
    specifications: { "Battery": "30h (with case)", "Noise Cancellation": "Active", "Waterproof": "IPX5", "Codec": "AAC, SBC" },
    colors: ["White", "Black", "Navy"],
    tags: ["earbuds", "wireless", "audio", "noise-cancelling"],
    seller: sellers[1], rating: 4.6, reviewCount: 234, warranty: "1 Year Warranty",
    deliveryOptions: [{ method: "Standard", price: 5000, estimatedDays: "1-2 days" }],
    featured: true, trending: true, status: "active", createdAt: "2024-03-01", updatedAt: "2024-03-15" },
  { id: "p18", name: "Premium Men's Leather Jacket", slug: "premium-mens-leather-jacket",
    description: "Genuine cowhide leather jacket with soft inner lining. Classic biker style with quilted shoulders.",
    price: 450000, discountPrice: 380000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80","https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=600&q=80"],
    category: "Fashion", brand: "LeatherCraft", sku: "MJ001", quantity: 35, sold: 145, condition: "new",
    specifications: { "Material": "Genuine Cowhide", "Lining": "Polyester", "Closure": "YKK Zipper", "Care": "Professional dry clean" },
    colors: ["Black", "Brown", "Dark Grey"], sizes: ["S", "M", "L", "XL", "2XL"],
    tags: ["jacket", "leather", "fashion", "men"],
    seller: sellers[0], rating: 4.7, reviewCount: 89, returnPolicy: "14 days return",
    deliveryOptions: [{ method: "Standard", price: 10000, estimatedDays: "2-3 days" }],
    featured: false, trending: true, status: "active", createdAt: "2024-03-05", updatedAt: "2024-03-15" },
  { id: "p19", name: "Premium Non-Slip Yoga Mat 6mm", slug: "premium-non-slip-yoga-mat",
    description: "Extra thick 6mm yoga mat with alignment lines. Non-slip TPE material, eco-friendly, and comes with carrying strap.",
    price: 65000, discountPrice: 52000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&q=80","https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?w=600&q=80"],
    category: "Sports", brand: "ZenFit", sku: "YM6MM", quantity: 90, sold: 340, condition: "new",
    specifications: { "Thickness": "6mm", "Material": "TPE", "Size": "183x61cm", "Weight": "1.2kg" },
    colors: ["Purple", "Teal", "Black", "Rose"],
    tags: ["yoga", "fitness", "sports", "exercise"],
    seller: sellers[5], rating: 4.5, reviewCount: 178, returnPolicy: "7 days return",
    deliveryOptions: [{ method: "Standard", price: 5000, estimatedDays: "1-3 days" }],
    featured: false, trending: false, status: "active", createdAt: "2024-03-01", updatedAt: "2024-03-10" },
  { id: "p20", name: "High-Speed Blender 1500W", slug: "high-speed-blender-1500w",
    description: "Professional-grade 1500W blender with 6 stainless steel blades, variable speed control, and 2L BPA-free pitcher.",
    price: 180000, discountPrice: 150000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&q=80","https://images.unsplash.com/photo-1559348274-b1dc4e18e899?w=600&q=80"],
    category: "Home & Kitchen", brand: "BlendMax", sku: "BL1500", quantity: 55, sold: 210, condition: "new",
    specifications: { "Power": "1500W", "Capacity": "2L", "Blades": "6 Stainless Steel", "Speeds": "12 + Pulse" },
    colors: ["Silver", "Black", "Red"],
    tags: ["blender", "kitchen", "appliance", "cooking"],
    seller: sellers[6], rating: 4.6, reviewCount: 123, warranty: "2 Year Warranty",
    deliveryOptions: [{ method: "Standard", price: 10000, estimatedDays: "2-3 days" }],
    featured: true, trending: false, status: "active", createdAt: "2024-02-20", updatedAt: "2024-03-01" },
  { id: "p21", name: "Lightweight Foldable Baby Stroller", slug: "lightweight-baby-stroller",
    description: "Ultra-compact foldable stroller for infants and toddlers. Features 5-point harness, sun canopy, and storage basket.",
    price: 320000, discountPrice: 275000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1594463750920-7a58b5e8c19b?w=600&q=80","https://images.unsplash.com/photo-1563770551469-0c6e328a0b2a?w=600&q=80"],
    category: "Baby Products", brand: "BabyGo", sku: "BGS100", quantity: 25, sold: 98, condition: "new",
    specifications: { "Weight": "7.5kg", "Age Range": "0-36 months", "Harness": "5-point", "Fold": "One-hand fold" },
    colors: ["Grey", "Navy", "Red"],
    tags: ["baby", "stroller", "baby-products", "travel"],
    seller: sellers[6], rating: 4.7, reviewCount: 67, warranty: "1 Year Warranty",
    deliveryOptions: [{ method: "Standard", price: 15000, estimatedDays: "3-5 days" }],
    featured: false, trending: true, status: "active", createdAt: "2024-03-10", updatedAt: "2024-03-15" },
  { id: "p22", name: "Vitamin C Brightening Serum 30ml", slug: "vitamin-c-brightening-serum",
    description: "Powerful 20% Vitamin C serum with hyaluronic acid and vitamin E. Brightens skin, reduces dark spots, and boosts collagen.",
    price: 45000, discountPrice: 36000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80","https://images.unsplash.com/photo-1570194065650-d99fb4ee8e39?w=600&q=80"],
    category: "Beauty", brand: "GlowLab", sku: "VCS30", quantity: 150, sold: 890, condition: "new",
    specifications: { "Volume": "30ml", "Concentration": "20% Vitamin C", "Key Ingredients": "Vitamin C, HA, Vitamin E", "Skin Type": "All skin types" },
    tags: ["beauty", "skincare", "serum", "vitamin-c"],
    seller: sellers[4], rating: 4.8, reviewCount: 445, returnPolicy: "7 days return",
    deliveryOptions: [{ method: "Standard", price: 3000, estimatedDays: "1-2 days" }],
    featured: true, trending: true, status: "active", createdAt: "2024-03-01", updatedAt: "2024-03-15" },
  { id: "p23", name: "LED Desk Lamp with Wireless Charger", slug: "led-desk-lamp-wireless-charger",
    description: "Smart LED desk lamp with 5 brightness levels, 3 color temperatures, built-in wireless charger, and USB charging port.",
    price: 95000, discountPrice: 78000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600&q=80","https://images.unsplash.com/photo-1534105461083-1c644260339b?w=600&q=80"],
    category: "Furniture", brand: "SmartLight", sku: "DLW001", quantity: 70, sold: 260, condition: "new",
    specifications: { "Brightness": "5 Levels", "Color Temp": "3000K-6500K", "Charging": "15W Wireless + USB-A", "Material": "Aluminum + ABS" },
    colors: ["White", "Black", "Silver"],
    tags: ["lamp", "desk", "led", "wireless-charger", "office"],
    seller: sellers[6], rating: 4.5, reviewCount: 156, warranty: "1 Year Warranty",
    deliveryOptions: [{ method: "Standard", price: 8000, estimatedDays: "2-3 days" }],
    featured: false, trending: false, status: "active", createdAt: "2024-03-05", updatedAt: "2024-03-10" },
  { id: "p24", name: "Portable Bluetooth Speaker IPX7", slug: "portable-bluetooth-speaker",
    description: "Rugged waterproof Bluetooth speaker with 360° sound, 20-hour battery life, built-in microphone, and USB-C charging.",
    price: 120000, discountPrice: 95000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80","https://images.unsplash.com/photo-1589003077984-894e133dabab?w=600&q=80"],
    category: "Electronics", brand: "BassBox", sku: "BBS100", quantity: 95, sold: 430, condition: "new",
    specifications: { "Battery": "20 hours", "Waterproof": "IPX7", "Output": "30W 360°", "Charging": "USB-C" },
    colors: ["Black", "Blue", "Green", "Red"],
    tags: ["speaker", "bluetooth", "portable", "audio"],
    seller: sellers[1], rating: 4.6, reviewCount: 312, warranty: "1 Year Warranty",
    deliveryOptions: [{ method: "Standard", price: 6000, estimatedDays: "1-3 days" }],
    featured: true, trending: false, status: "active", createdAt: "2024-02-25", updatedAt: "2024-03-10" },
  { id: "p25", name: "Electric Hand Mixer 5-Speed", slug: "electric-hand-mixer-5-speed",
    description: "Powerful 300W hand mixer with 5 speeds, turbo button, stainless steel beaters, and dough hooks for all your baking needs.",
    price: 65000, discountPrice: 52000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&q=80","https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&q=80"],
    category: "Home & Kitchen", brand: "MixMaster", sku: "HM5SPD", quantity: 80, sold: 310, condition: "new",
    specifications: { "Power": "300W", "Speeds": "5 + Turbo", "Accessories": "Beaters & Dough Hooks", "Material": "Stainless Steel" },
    colors: ["White", "Black", "Red"],
    tags: ["kitchen", "mixer", "baking", "appliance"],
    seller: sellers[6], rating: 4.5, reviewCount: 98, warranty: "1 Year Warranty",
    deliveryOptions: [{ method: "Standard", price: 7000, estimatedDays: "2-3 days" }],
    featured: false, trending: false, status: "active", createdAt: "2024-03-15", updatedAt: "2024-03-20" },
  { id: "p26", name: "Wireless Gaming Mouse RGB 16000 DPI", slug: "wireless-gaming-mouse-rgb",
    description: "Ultra-light 58g wireless gaming mouse with PixArt sensor, 16000 DPI, 80h battery, and customizable RGB lighting.",
    price: 85000, discountPrice: 68000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1527814050087-3793815479db?w=600&q=80","https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&q=80"],
    category: "Gaming", brand: "GameClaw", sku: "GM800", quantity: 65, sold: 280, condition: "new",
    specifications: { "DPI": "16000", "Weight": "58g", "Battery": "80 hours", "Connectivity": "2.4GHz + Bluetooth" },
    colors: ["Black", "White"],
    tags: ["gaming", "mouse", "wireless", "rgb"],
    seller: sellers[1], rating: 4.6, reviewCount: 167, warranty: "1 Year Warranty",
    deliveryOptions: [{ method: "Standard", price: 5000, estimatedDays: "1-3 days" }],
    featured: true, trending: true, status: "active", createdAt: "2024-03-20", updatedAt: "2024-03-25" },
  { id: "p27", name: "Organic Honey - Pure Raw 500g", slug: "organic-honey-pure-raw-500g",
    description: "Pure raw organic honey harvested from the forests of Tanzania. Unfiltered, unpasteurized, and rich in natural enzymes.",
    price: 25000, discountPrice: 20000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80","https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600&q=80"],
    category: "Groceries", brand: "Tz Wild Honey", sku: "HNY500", quantity: 200, sold: 890, condition: "new",
    specifications: { "Weight": "500g", "Type": "Raw Organic", "Origin": "Tanzania", "Shelf Life": "24 months" },
    tags: ["honey", "organic", "groceries", "natural"],
    seller: sellers[2], rating: 4.9, reviewCount: 234,
    deliveryOptions: [{ method: "Standard", price: 3000, estimatedDays: "1-2 days" }],
    featured: false, trending: true, status: "active", createdAt: "2024-03-01", updatedAt: "2024-03-20" },
  { id: "p28", name: "Fitness Tracker Smart Band", slug: "fitness-tracker-smart-band",
    description: "Advanced fitness tracker with heart rate monitor, SpO2, sleep tracking, 14-day battery, and water-resistant design.",
    price: 55000, discountPrice: 42000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1576243345690-4e4b79b63288?w=600&q=80","https://images.unsplash.com/photo-1557935728-e6d1eaabe558?w=600&q=80"],
    category: "Electronics", brand: "FitBand", sku: "FT100", quantity: 110, sold: 560, condition: "new",
    specifications: { "Battery": "14 days", "Sensors": "HR, SpO2, Sleep", "Waterproof": "IP68", "Display": "AMOLED 1.47\"" },
    colors: ["Black", "Navy", "Pink"],
    tags: ["fitness", "tracker", "smart-band", "health"],
    seller: sellers[5], rating: 4.4, reviewCount: 345, warranty: "6 Months",
    deliveryOptions: [{ method: "Standard", price: 4000, estimatedDays: "1-3 days" }],
    featured: true, trending: true, status: "active", createdAt: "2024-03-10", updatedAt: "2024-03-20" },
  { id: "p29", name: "Stainless Steel Water Bottle 1L", slug: "stainless-steel-water-bottle-1l",
    description: "Double-wall vacuum insulated bottle. Keeps drinks cold 24h or hot 12h. BPA-free, leak-proof, and eco-friendly.",
    price: 35000, discountPrice: 28000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80","https://images.unsplash.com/photo-1570831739435-6601aa3fa4fb?w=600&q=80"],
    category: "Sports", brand: "HydroMax", sku: "HB1L", quantity: 150, sold: 720, condition: "new",
    specifications: { "Capacity": "1L", "Material": "Stainless Steel", "Insulation": "Double-wall Vacuum", "Weight": "380g" },
    colors: ["Stainless", "Matte Black", "Ocean Blue", "Rose Gold"],
    tags: ["bottle", "water", "sports", "eco-friendly"],
    seller: sellers[5], rating: 4.7, reviewCount: 412, returnPolicy: "14 days return",
    deliveryOptions: [{ method: "Standard", price: 3000, estimatedDays: "1-2 days" }],
    featured: false, trending: false, status: "active", createdAt: "2024-03-05", updatedAt: "2024-03-15" },
  { id: "p30", name: "Scented Candle Set - 3 Pieces", slug: "scented-candle-set-3-pieces",
    description: "Hand-poured soy wax candle set. Available in vanilla, lavender, and cinnamon. 40+ hours burn time each.",
    price: 28000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&q=80","https://images.unsplash.com/photo-1602523961358-f9cf8c1f0fc0?w=600&q=80"],
    category: "Home & Kitchen", brand: "ScentHome", sku: "SCS3", quantity: 90, sold: 410, condition: "new",
    specifications: { "Pieces": "3", "Type": "Soy Wax", "Burn Time": "40h each", "Scents": "Vanilla, Lavender, Cinnamon" },
    tags: ["candles", "home", "decor", "gift"],
    seller: sellers[6], rating: 4.8, reviewCount: 189, returnPolicy: "7 days return",
    deliveryOptions: [{ method: "Standard", price: 4000, estimatedDays: "1-2 days" }],
    featured: false, trending: false, status: "active", createdAt: "2024-03-15", updatedAt: "2024-03-20" },
  { id: "p31", name: "Men's Casual Sneakers - Breathable Mesh", slug: "mens-casual-sneakers-mesh",
    description: "Lightweight breathable mesh sneakers with memory foam insole. Perfect for daily wear, walking, and light sports.",
    price: 75000, discountPrice: 58000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&q=80","https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80"],
    category: "Shoes", brand: "UrbanStep", sku: "SNK001", quantity: 75, sold: 340, condition: "new",
    specifications: { "Material": "Breathable Mesh", "Sole": "Rubber", "Closure": "Lace-up", "Insole": "Memory Foam" },
    colors: ["Black", "White", "Navy", "Grey"], sizes: ["39", "40", "41", "42", "43", "44", "45"],
    tags: ["sneakers", "shoes", "men", "casual"],
    seller: sellers[0], rating: 4.5, reviewCount: 234, returnPolicy: "14 days return",
    deliveryOptions: [{ method: "Standard", price: 6000, estimatedDays: "1-3 days" }],
    featured: true, trending: true, status: "active", createdAt: "2024-03-20", updatedAt: "2024-03-25" },
  { id: "p32", name: "Anti-Aging Night Cream 50ml", slug: "anti-aging-night-cream-50ml",
    description: "Luxurious night cream with retinol, hyaluronic acid, and vitamin E. Reduces fine lines and improves skin elasticity overnight.",
    price: 42000, discountPrice: 34000, currency: "TZS",
    images: ["https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&q=80","https://images.unsplash.com/photo-1617897903246-719242758050?w=600&q=80"],
    category: "Beauty", brand: "DermaGlow", sku: "NC50", quantity: 60, sold: 290, condition: "new",
    specifications: { "Volume": "50ml", "Key Ingredients": "Retinol, HA, Vitamin E", "Skin Type": "All skin types", "Usage": "Apply nightly" },
    tags: ["beauty", "skincare", "anti-aging", "cream"],
    seller: sellers[4], rating: 4.7, reviewCount: 178, returnPolicy: "7 days return",
    deliveryOptions: [{ method: "Standard", price: 4000, estimatedDays: "1-2 days" }],
    featured: false, trending: false, status: "active", createdAt: "2024-03-10", updatedAt: "2024-03-20" },
];

// ===== Flash Sales =====
export const flashSales: FlashSale[] = [
  { id: "fs-1", title: "Flash Sale", description: "Limited time deals you can't miss!",
    products: [products[0], products[2], products[4], products[5], products[6]],
    startTime: new Date().toISOString(), endTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    discount: 40, isActive: true },
];

// ===== Reviews =====
export const reviews: Review[] = [
  { id: "rev-1", userId: "u1", userName: "Sarah M.", userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80", productId: "p1", rating: 5, title: "Absolutely love it!", comment: "The iPhone 15 Pro Max exceeded all my expectations.", likes: 24, createdAt: "2024-01-28" },
  { id: "rev-2", userId: "u2", userName: "David K.", userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80", productId: "p1", rating: 4, title: "Great phone, premium price", comment: "Best iPhone yet. The titanium build feels premium.", likes: 12, createdAt: "2024-01-25" },
];

// ===== Testimonials =====
export const testimonials: Testimonial[] = [
  { id: "test-1", name: "Neema Hassan", role: "Fashion Boutique Owner", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80", content: "SokoDigital transformed my business. I went from selling locally to reaching customers across all of Tanzania.", rating: 5 },
  { id: "test-2", name: "Kevin Mushi", role: "Tech Enthusiast", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80", content: "Finally, a marketplace that understands Tanzania. Fast delivery, secure payments, and real verified sellers.", rating: 5 },
  { id: "test-3", name: "Aisha Salum", role: "Home Baker", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80", content: "The AI assistant helped me find exactly what I needed within my budget. Shopping has never been this easy!", rating: 5 },
  { id: "test-4", name: "Joseph Lema", role: "University Student", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80", content: "As a student, finding affordable electronics was always a challenge. SokoDigital's deals and verified sellers make it stress-free.", rating: 4 },
];

// ===== Banners =====
export const banners: Banner[] = [
  // ── Banner 1 ──
  {
    id: "b1",
    title: "Everything You Need, All in One Place",
    subtitle: "Discover thousands of quality products with amazing prices and fast delivery across Tanzania.",
    description: "From electronics and fashion to groceries and beauty — SokoDigital has it all, delivered to your door.",
    cta: "Shop Now",
    link: "/marketplace",
    desktopImage: banner1Img,
    mobileImage: banner1Img,
    badge: "Premium Marketplace",
    type: "hero",
    priority: 1,
    isActive: true,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    bgColor: "#F97316",
    textColor: "#111827",
  },
  // ── Banner 2 ──
  {
    id: "b2",
    title: "Flash Sale Up to 70% OFF",
    subtitle: "Limited-time offers on your favorite products. Don't miss out!",
    description: "Grab amazing deals on smartphones, laptops, fashion, accessories, and more before they're gone.",
    cta: "Grab Deals",
    link: "/marketplace?sort=discount",
    desktopImage: banner2Img,
    mobileImage: banner2Img,
    badge: "Flash Sale",
    discount: 70,
    type: "hero",
    priority: 2,
    isActive: true,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    bgColor: "#F97316",
    textColor: "#111827",
  },
  // ── Banner 3 ──
  {
    id: "b3",
    title: "Glow with Premium Beauty",
    subtitle: "Discover authentic skincare, makeup, perfumes, and beauty essentials from trusted brands.",
    description: "From luxury skincare to everyday essentials — elevate your beauty routine with SokoDigital.",
    cta: "Shop Cosmetics",
    link: "/marketplace?category=beauty",
    desktopImage: banner3Img,
    mobileImage: banner3Img,
    badge: "Cosmetics",
    type: "hero",
    priority: 3,
    isActive: true,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    bgColor: "#FB923C",
    textColor: "#111827",
  },
  // ── Banner 4 ──
  {
    id: "b4",
    title: "Fast Delivery. Secure Payments. Trusted Sellers.",
    subtitle: "Shop confidently with secure checkout and nationwide delivery across Tanzania Mainland & Zanzibar.",
    description: "Free delivery on orders over 50,000 TZS. Real-time tracking. 14-day returns. Shop with peace of mind.",
    cta: "Start Shopping",
    link: "/marketplace",
    desktopImage: banner4Img,
    mobileImage: banner4Img,
    badge: "Free Delivery",
    type: "hero",
    priority: 4,
    isActive: true,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    bgColor: "#F97316",
    textColor: "#111827",
  },
  // ── Banner 5 ──
  {
    id: "b5",
    title: "Shop the Latest Deals",
    subtitle: "Discover amazing offers on top brands with exclusive discounts and fast delivery.",
    description: "From gadgets to groceries — find everything you need at prices you'll love.",
    cta: "Explore Now",
    link: "/marketplace",
    desktopImage: banner5Img,
    mobileImage: banner5Img,
    badge: "New Arrivals",
    type: "hero",
    priority: 5,
    isActive: true,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    bgColor: "#F97316",
    textColor: "#111827",
  },
];

// ===== Notifications =====
export const notifications: Notification[] = [
  { id: "notif-1", type: "order", title: "Order Confirmed", message: "Your iPhone 15 Pro Max order has been confirmed", read: false, createdAt: new Date().toISOString() },
  { id: "notif-2", type: "promotion", title: "Flash Sale Alert!", message: "Up to 60% off on electronics. Limited time only!", read: false, createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: "notif-3", type: "message", title: "New Message from Seller", message: "TechZone responded to your inquiry", read: true, createdAt: new Date(Date.now() - 7200000).toISOString() },
];

// ===== AI Suggestions =====
export const aiSuggestions: AISuggestion[] = [
  { id: "ai-1", text: "Find a laptop under 500,000 TZS", icon: "Monitor", category: "computers" },
  { id: "ai-2", text: "Recommend a good phone for photography", icon: "Camera", category: "phones" },
  { id: "ai-3", text: "Compare iPhone 15 vs Samsung S24", icon: "GitCompare", category: "phones" },
  { id: "ai-4", text: "Find cheaper alternatives to AirPods", icon: "Headphones", category: "electronics" },
  { id: "ai-5", text: "Suggest birthday gift for my mom", icon: "Gift", category: "general" },
  { id: "ai-6", text: "What's trending in Dar es Salaam?", icon: "TrendingUp", category: "trending" },
  { id: "ai-7", text: "Find fashion deals under 50,000 TZS", icon: "ShoppingBag", category: "fashion" },
  { id: "ai-8", text: "Best gaming laptop recommendations", icon: "Gamepad2", category: "gaming" },
];

// ===== Helper Functions =====
export function formatTZS(amount: number): string {
  return new Intl.NumberFormat("sw-TZ", { style: "currency", currency: "TZS", minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(amount);
}
export function formatDiscount(price: number, discounted: number): number {
  return Math.round(((price - discounted) / price) * 100);
}
export function getRatingColor(rating: number): string {
  if (rating >= 4.5) return "text-emerald-500";
  if (rating >= 4) return "text-blue-500";
  if (rating >= 3) return "text-amber-500";
  return "text-red-500";
}
export function getTimeRemaining(endTime: string): { hours: number; minutes: number; seconds: number } {
  const total = Date.parse(endTime) - Date.now();
  if (total <= 0) return { hours: 0, minutes: 0, seconds: 0 };
  return {
    hours: Math.floor(total / (1000 * 60 * 60)),
    minutes: Math.floor((total / (1000 * 60)) % 60),
    seconds: Math.floor((total / 1000) % 60),
  };
}

// ===== Languages =====
export const languages = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
];

// ===== Trending Searches =====
export const trendingSearches = [
  "iPhone 15 Pro", "Kitenge dresses", "Smart TVs", "Laptop deals",
  "M-Pesa phones", "Furniture", "Sneakers", "Beauty products", "Gaming chair",
];

// ===== Footer Links =====
export const footerLinks: Record<string, string[]> = {
  "Sell on SokoDigital": ["Become a Vendor", "Become a Manufacturer", "Seller Dashboard", "Seller Academy", "Advertising"],
  "Get Support": ["Help Center", "Check Order Status", "Live Chat", "Refund Policy", "Contact Us"],
  "Payment & Protection": ["Safe and Easy Payment", "Money Back Policy", "On-Time Shipping", "After Sales Protection", "Secure Checkout"],
  "Resources": ["SokoDigital Logistics", "Sales Tax & VAT", "Shipping Info", "Returns Center", "FAQ"],
  "Get to Know Us": ["About SokoDigital", "Corporate Responsibility", "News Center", "Careers", "Press Kit"],
};

// ===== Payment Methods =====
export const paymentMethods = [
  { id: "mpesa", name: "M-Pesa", icon: "Smartphone", description: "Pay with M-Pesa mobile money" },
  { id: "airtel", name: "Airtel Money", icon: "Smartphone", description: "Pay with Airtel Money" },
  { id: "mixx", name: "Mixx by Yas", icon: "Smartphone", description: "Pay with Mixx" },
  { id: "halopesa", name: "HaloPesa", icon: "Smartphone", description: "Pay with HaloPesa" },
  { id: "visa", name: "Visa", icon: "CreditCard", description: "Pay with Visa card" },
  { id: "mastercard", name: "Mastercard", icon: "CreditCard", description: "Pay with Mastercard" },
  { id: "crdb", name: "CRDB Bank", icon: "Landmark", description: "Pay with CRDB Bank" },
  { id: "nmb", name: "NMB Bank", icon: "Landmark", description: "Pay with NMB Bank" },
  { id: "nbc", name: "NBC Bank", icon: "Landmark", description: "Pay with NBC Bank" },
];

// ===== Export aliases =====
export const flashSale = flashSales;

export const formatDate = (date: string): string => {
  return new Date(date).toLocaleDateString("en-TZ", { year: "numeric", month: "long", day: "numeric" });
};
export const formatDateShort = (date: string): string => {
  return new Date(date).toLocaleDateString("en-TZ", { month: "short", day: "numeric" });
};
